apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  labels:
    app.kubernetes.io/part-of: java-web-app
    apps.tanzu.vmware.com/has-docs: "true"
    apps.tanzu.vmware.com/workload-type: web
  name: java-web-app
  namespace: default
spec:
  source:
    git:
      ref:
        branch: main
      url: https://github.com/vrabbi/java-web-app
